/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = require('./webpack.config.base')({
  // Add hot reloading in development
  entry: {
    'webpack-hot-middleware': 'webpack-hot-middleware/client',
    main: path.join(process.cwd(), 'app/main.js')
  },

  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js'
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new webpack.NoErrorsPlugin(),
    new HtmlWebpackPlugin({
      template: path.resolve('app/index.html'),
      hash: false,
      inject: true // Inject all files that are generated by webpack, e.g. bundle.js
    })
  ], // eslint-disable-line no-use-before-define

  // Tell babel that we want to hot-reload
  babelQuery: {
    presets: ['react-hmre']
  },

  // Emit a source map for easier debugging
  devtool: 'cheap-module-eval-source-map'
});
